// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaQgc0IVapyN7zqrC4zvb1_NDidtZv9_U',
    appId: '1:900351344597:web:8dd77cd32a8fa5231f075c',
    messagingSenderId: '900351344597',
    projectId: 'paper-prayer',
    authDomain: 'paper-prayer.firebaseapp.com',
    storageBucket: 'paper-prayer.firebasestorage.app',
    measurementId: 'G-X2MC81C70M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMIRZJuitMlole-tCKVUxsaJSQ_gIglqg',
    appId: '1:900351344597:android:9ec58cafae6045201f075c',
    messagingSenderId: '900351344597',
    projectId: 'paper-prayer',
    storageBucket: 'paper-prayer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdBT4qJFbN6PUP4GCjqO0Cm9JBQAMYQ2U',
    appId: '1:900351344597:ios:373c06d557db4baf1f075c',
    messagingSenderId: '900351344597',
    projectId: 'paper-prayer',
    storageBucket: 'paper-prayer.firebasestorage.app',
    iosBundleId: 'com.example.prayerMl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdBT4qJFbN6PUP4GCjqO0Cm9JBQAMYQ2U',
    appId: '1:900351344597:ios:373c06d557db4baf1f075c',
    messagingSenderId: '900351344597',
    projectId: 'paper-prayer',
    storageBucket: 'paper-prayer.firebasestorage.app',
    iosBundleId: 'com.example.prayerMl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQgc0IVapyN7zqrC4zvb1_NDidtZv9_U',
    appId: '1:900351344597:web:aad9747f66796b4c1f075c',
    messagingSenderId: '900351344597',
    projectId: 'paper-prayer',
    authDomain: 'paper-prayer.firebaseapp.com',
    storageBucket: 'paper-prayer.firebasestorage.app',
    measurementId: 'G-YGJX7PEFSQ',
  );
}
